package Exception;

public class exceptionTest {
    public static void main(String[] args) throws Exception {
        int num1 = 10, num2 = 0;

            //int c = num1 / num2;
        int num3 = 4 /  num2;
            //throw new RuntimeException(e);
            System.out.println("error...");

        System.out.println("程序继续执行...");
    }
}
